[package]
name = "wldash"
version = "0.3.0"
authors = ["Kenny Levinsen <kl@kl.wtf>"]
edition = "2018"

[profile.release]
lto = "fat"
panic = "abort"
opt-level = "z"

[features]
default = ["alsa-widget", "pulseaudio-widget", "yaml-cfg", "json-cfg"]
damage_debug = []

yaml-cfg = ["serde_yaml"]
json-cfg = ["serde_json"]

alsa-widget = ["alsa"]
pulseaudio-widget = ["libpulse-binding"]

[dependencies]
byteorder = "1.3"
bitflags = "1.0"
dlib = "0.4"
rusttype = "^0.9"
chrono = "0.4"
nix = "0.16"
memmap = "0.7"
os_pipe = "0.9"
wayland-client = { version = "0.28"}
wayland-protocols = { version = "0.28", features = ["client", "unstable_protocols"] }
dbus = "0.6"
fuzzy-matcher = "0.3"
lazy_static = "1.4"
rcalc_lib = "0.9"
rust-ini = "0.14"
shlex = "0.1"
timerfd = "1.0.0"
walkdir = "2.3.2"
itertools = "0.10.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.8", optional = true }

libpulse-binding = { version = "2.22", optional = true }
alsa = { version = "0.4.0", optional = true }
fontconfig = "0.2.0"
unicode-segmentation = "1.6.0"
